# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Crafter's Circle
encoding: utf-8 # Make sure the encoding is right
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog about crafting software, the software industry, and anything
  that we like to speak about.
  This blog is written by Antoine BOILEAU, Christophe THIBAUT, and Thomas WICKHAM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crafterscirle.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: apemb # jekyll-seo-tag > Owners twitter username
author: Antoine Boileau # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Antoine Boileau # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/apemb

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Paris # Timezone for blog posts and alike

# Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  Authors: /authors/
  #Categories: /categories/

navigation_footer:
  Created by David Darnes: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  LinkedIn: "#0077B5"
  # Reddit: "#FF4500"
  # Email: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: alembic-jekyll-theme

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
